name: backend pipeline

on:
  pull_request: {}
  push:
    branches:
      - main
    paths-ignore: 
      - "README.md" 
      - "docs/**" 
      - "frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
        with: 
          node-version: '12'
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Testing
        working-directory: ./backend
        run: npm test