name: frontend pipeline

on:
  push:
    branches:
      - main
    paths-ignore: 
      - "README.md" 
      - "docs/**" 
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
        with: 
          node-version: '12'
      - run: npm install
      - run: npm test